### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by puyt** [tinytacoteam/zazu-snippets#6]
### Zazu Info
- App Environment: production
- App Version: 0.2.3
- Electron Version: 1.3.8
- Node Version: 6.5.0
- Chrome Version: 52.0.2743.82

### Problem
Creating and deleting snippets works fine but searching doesn't give any results only the fallback results such as search on google.

I've created a snippet called `test` and I can see the snippet inside the folder but nothing comes up when I use `snip test` in zazu

### Log:
```
{"input":"snip test","respondsTo":["snip test","test"],"plugin":"tinytacoteam/zazu-snippets","block":"Read","level":"info","message":"respondsTo","timestamp":"2017-01-06T12:59:18.274Z"}
{"input":"snip test","respondsTo":["snip test","test"],"plugin":"tinytacoteam/zazu-snippets","block":"Read","level":"info","message":"respondsTo","timestamp":"2017-01-06T12:59:18.297Z"}
{"query":"test","plugin":"tinytacoteam/zazu-snippets","block":"Read","level":"verbose","message":"Executing Script","timestamp":"2017-01-06T12:59:18.301Z"}
{"input":"snip test","respondsTo":null,"plugin":"tinytacoteam/zazu-snippets","block":"Write","level":"info","message":"respondsTo","timestamp":"2017-01-06T12:59:18.303Z"}
{"input":"snip test","respondsTo":null,"plugin":"tinytacoteam/zazu-snippets","block":"Delete","level":"info","message":"respondsTo","timestamp":"2017-01-06T12:59:18.305Z"}
{"query":"test","error":{},"plugin":"tinytacoteam/zazu-snippets","block":"Read","level":"error","message":"Script failed","timestamp":"2017-01-06T12:59:18.321Z"}
```

**Comment by bayleedev** [comment]
Thank you for reporting! I'll take a look.

**Comment by puyt** [comment]
Oh and i'm running zazu on macOs Sierra 10.12.1

**Comment by afaur** [comment]
@Sven-Depondt I looked at this and pushed up (https://github.com/tinytacoteam/zazu-snippets/commit/8f8eb22a7d27b74e5f107d2c0baae92da7959e26) which should resolve this issue.  

Seems to be functioning on my machine now, but please let me know if this works for you.

**Comment by puyt** [comment]
@afaur It is indeed working. Thanks!
